### ISSUE TITLE
Error when closing the main window.

### ISSUE THREAD

**Issue by hendo-michael** [CSSE1001/MyPyTutor#112]
Inside 'code/tutorlib/interface/interpreter.py' when it calls __delete__()  it is trying to remove a file/directory that does not exist.

It is calling "os.remove(self.path)

**Comment by sapi** [comment]
Can you post the traceback please? I'd like to see the exact context,
because I can't think what would be causing the problem there.

**Comment by hendo-michael** [comment]
Exception ignored in: <bound method Interpreter.__del__ of <tutorlib.interface.interpreter.Interpreter object at 0x7f3f57e87588>>
Traceback (most recent call last):
  File "/home/michael/Documents/Github/MyPyTutor/code/tutorlib/interface/interpreter.py", line 37, in __del__
    os.remove(self.path)  # will gen before removing, but meh
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp3oemkc6y'
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCall._ComplexBinder object at 0x7f3f57eb1ac8>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/idlelib/MultiCall.py", line 244, in __del__
    self.widget.unbind(self.widgetinst, seq, id)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1095, in unbind
    self.tk.call('bind', self._w, sequence, '')
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCall._ComplexBinder object at 0x7f3f57eb1f28>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/idlelib/MultiCall.py", line 244, in __del__
    self.widget.unbind(self.widgetinst, seq, id)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1095, in unbind
    self.tk.call('bind', self._w, sequence, '')
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCall._ComplexBinder object at 0x7f3f57cc0898>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/idlelib/MultiCall.py", line 244, in __del__
    self.widget.unbind(self.widgetinst, seq, id)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1095, in unbind
    self.tk.call('bind', self._w, sequence, '')
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCall._ComplexBinder object at 0x7f3f57cc08d0>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/idlelib/MultiCall.py", line 244, in __del__
    self.widget.unbind(self.widgetinst, seq, id)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1095, in unbind
    self.tk.call('bind', self._w, sequence, '')
_tkinter.TclError: can't invoke "bind" command: application has been destroyed

**Comment by hendo-michael** [comment]
This is in Ubuntu 14.10

**Comment by hendo-michael** [comment]
If you close the main window while the login window is still open you get this error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1536, in __call__
    return self.func(*args)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 585, in callit
    func(*args)
  File "/home/michael/Documents/Github/MyPyTutor/code/tutorlib/gui/app/app.py", line 564, in login
    logged_in_user=self.web_api.user if logged_in else None
  File "/home/michael/Documents/Github/MyPyTutor/code/tutorlib/gui/app/app.py", line 315, in _set_online_status
    self.online_status.config(text='Status: Not Logged In')
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1322, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1313, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".140635446834344.140635446834736.140635446835016"

**Comment by jgat** [comment]
I also managed to produce some error when closing, though I forget the steps I took (e.g. which window I closed, etc.):
```
Exception ignored in: <bound method Interpreter.__del__ of <tutorlib.interface.interpreter.Interpreter object at 0x10a1fe2e8>>
Traceback (most recent call last):
  File "/Users/jackson/uni-repos/csse1001/MyPyTutor/code/tutorlib/interface/interpreter.py", line 37, in __del__
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/_6/zn9k8v8s3bv1dyckpmy1xx2c0000gn/T/tmptemn1ixc'
```

**Comment by pjritee** [comment]
I get the same (first) error as hendo when I close (every time)
