### ISSUE TITLE
Error on close when running MyPyTutor in IDLE

### ISSUE THREAD

**Issue by hendo-michael** [CSSE1001/MyPyTutor#134]
If I open MyPyTutor in IDLE and then run it I am getting errors when I go to close it.

If you open up a tutorial question and then close the editor window the main window does not close.
- When you then go to close the main window you get errors (shown below) and are unable to close MyPyTutor.
- When you go to open a new question the editor window does not show and you get more errors.

**Comment by hendo-michael** [comment]
Error when attempting to close the main window (after closing the editor window):

>>> Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\idlelib\run.py", line 121, in main
    seq, request = rpc.request_queue.get(block=True, timeout=0.05)
  File "C:\Python34\lib\queue.py", line 175, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Michael\Documents\mpt-install\tutorlib\gui\app\app.py", line 341, in close
    if self.editor.close() == tkmessagebox.YES:
  File "C:\Users\Michael\Documents\mpt-install\tutorlib\gui\editor\editor_window.py", line 149, in close
    self._close()
  File "C:\Python34\lib\idlelib\EditorWindow.py", line 1035, in _close
    if self.io.filename:
AttributeError: 'NoneType' object has no attribute 'filename'

**Comment by hendo-michael** [comment]
Error when attempting to open a new question (after closing the editor window and the main window remains open):

 Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\idlelib\run.py", line 121, in main
    seq, request = rpc.request_queue.get(block=True, timeout=0.05)
  File "C:\Python34\lib\queue.py", line 175, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Michael\Documents\mpt-install\tutorlib\gui\app\menu.py", line 262, in <lambda>
    cb = (lambda t=tutorial: lambda: self.problem_callback(t))()
  File "C:\Users\Michael\Documents\mpt-install\tutorlib\gui\app\menu.py", line 215, in problem_callback
    self.delegate.change_problem(problem=tutorial)
  File "C:\Users\Michael\Documents\mpt-install\tutorlib\utils\decorators.py", line 10, in method
    return f(self, *args, **kwargs)
  File "C:\Users\Michael\Documents\mpt-install\tutorlib\gui\app\app.py", line 509, in change_problem
    self.editor.reset(self.current_tutorial)
  File "C:\Users\Michael\Documents\mpt-install\tutorlib\gui\editor\editor_window.py", line 159, in reset
    self.set_text(self.tutorial.preload_code_text)
  File "C:\Users\Michael\Documents\mpt-install\tutorlib\gui\editor\editor_window.py", line 163, in set_text
    self.text.delete(1.0, tk.END)
AttributeError: 'NoneType' object has no attribute 'delete'

**Comment by sapi** [comment]
The self.io.filename one is a legitimate problem, but I can't seem to reproduce it. Any chance you could post the exact steps you went through?

I'm not fussed about errors running through IDLE. You'll always have problems running Tk apps through IDLE; running apps which use idlelib (which depends heavily on globals) is a bit much to ask.

**Comment by hendo-michael** [comment]
This does not happen when you run MyPyTutor from the command line. I am running the new_installer under windows 8.1.

**Comment by hendo-michael** [comment]
It is also fine when you run the (.pyw) file.

**Comment by hendo-michael** [comment]
- Opened MyPyTutor.py in IDLE (pressed F5)
- Opened a tutorial question
- Closed the editor window for the question (the main window remains open)
- Try and close the main window and get errors
OR
- Try and open a new question and the editor window no longer appears (also get errors)

**Comment by sapi** [comment]
Thanks for the info, but if it's just from running in IDLE, I don't think it's worth the effort of fixing (if fixing it is even possible).

If you are ever able to close the editor window without the whole app closing, I would be very interested to hear about it.  I've experienced that in the past, but never in a reproducible manner.
