### ISSUE TITLE
Updating answers folder in preferences menu

### ISSUE THREAD

**Issue by hendo-michael** [CSSE1001/MyPyTutor#50]
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1536, in __call__
    return self.func(*args)
  File "/home/michael/Documents/Github/MyPyTutor/code/tutorlib/gui/app/menu.py", line 180, in <lambda>
    callback = (lambda n=cb_name: lambda evt=None: self.callback(n))()
  File "/home/michael/Documents/Github/MyPyTutor/code/tutorlib/gui/app/menu.py", line 208, in callback
    return method()
  File "/home/michael/Documents/Github/MyPyTutor/code/tutorlib/gui/app/menu.py", line 323, in menu_preferences_answers_directory
    self.delegate.change_answers_directory()
  File "/home/michael/Documents/Github/MyPyTutor/code/tutorlib/gui/app/app.py", line 737, in change_answers_directory
    self.current_tutorial.name
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by sapi** [comment]
Thanks; that should be resolved.

I haven't had a chance to check (as things aren't working on OS X at all atm), but it looks like the classic error of accessing an uninitialised variable ><
