### ISSUE TITLE
MPT shutdown bug

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#77]
I get:
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCall._ComplexBinder object at 0x7f2db056e550>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/idlelib/MultiCall.py", line 244, in __del__
    self.widget.unbind(self.widgetinst, seq, id)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1044, in unbind
    self.tk.call('bind', self._w, sequence, '')
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCall._ComplexBinder object at 0x7f2db056ecf8>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/idlelib/MultiCall.py", line 244, in __del__
    self.widget.unbind(self.widgetinst, seq, id)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1044, in unbind
    self.tk.call('bind', self._w, sequence, '')
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCall._ComplexBinder object at 0x7f2db173ec18>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/idlelib/MultiCall.py", line 244, in __del__
    self.widget.unbind(self.widgetinst, seq, id)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1044, in unbind
    self.tk.call('bind', self._w, sequence, '')
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCall._ComplexBinder object at 0x7f2db056e588>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/idlelib/MultiCall.py", line 244, in __del__
    self.widget.unbind(self.widgetinst, seq, id)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1044, in unbind
    self.tk.call('bind', self._w, sequence, '')
_tkinter.TclError: can't invoke "bind" command: application has been destroyed

**Comment by sapi** [comment]
Thanks, but I've already got this open in #18

I think it's idlelib; I'm not creating those kind of callbacks, and it doesn't seem to appear unless the code window has been opened.
